name: haddock3
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.9
    - pip
    - numpy
    - jsonpickle
    - tox
    - pip:
        - pdb-tools==2.4.1
        - git+https://github.com/joaorodrigues/fcc@fcc2
