name: haddock3
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - numpy
  - jsonpickle
  - tox
  - pandas
  - pip:
      - pdb-tools
      - git+https://github.com/joaorodrigues/fcc@fcc2
