#===========================================================#
title = "HADDOCK3 Setup file"
#===========================================================#
[molecules]
mol1 = "e2aP_1F3G.pdb"
segid1 = "A"

mol2 = "hpr_ensemble.pdb"

[restraints]
ambig = 'e2a-hpr_air.tbl'

[identifier]
run = 'protein-protein-example'

[execution_parameters]
scheme = 'parallel'
nproc = 24

[stage]
# Stage specific parameters

[stage.topology]
recipe='default'
params.log_level="quiet"

[stage.rigid_body]
recipe='default'
sampling = 10