#===========================================================#
title = "HADDOCK3 Setup file"
#===========================================================#
[molecules]
mol1 = '1AY7_r_u.pdb'
#mol1.segid = "A"
mol2 = '1AY7_l_u.pdb'
#mol2.segid = "B"

[restraints]
ambig = 'ambig.tbl'

[identifier]
run = 1

[execution_parameters]
scheme = 'parallel'
nproc = 24

# Stage specific parameters
[stage]

[stage.topology]
recipe='default'

[stage.rigid_body]
recipe='rigid-body-minimal.cns'
sampling = 10

params.auto_his = true

[stage.semi_flexible]
recipe='default'
sampling = 5

[stage.water_refinement]
recipe='default'
sampling = 5
#===========================================================#