#===========================================================#
title = "HADDOCK3 Scoring Workflow Setup file"
#===========================================================#
[molecules]
mol1 = 'traj_ensemble.pdb'

[identifier]
run = 1

[execution_parameters]
scheme = 'parallel'
nproc = 24

[stage]
# Stage specific parameters

[stage.scoring]
recipe='default'

params.log_level="quiet"

#===========================================================#