# Recipe: LightDock integration with HADDOCK scoring

# A recipe is composed by different stages which are executed in
# by index in the order field:
order = ["topology", "sampling", "scoring"]

[stage]

#####################################################################-1
[stage.topology]
flavour = "default"
autohis = true

# Definition of the input molecules:
[[stage.topology.molecules]]
[[stage.topology.molecules.1]]
file = "2oob.pdb"

#####################################################################-2
[stage.sampling]
flavour = "lightdock"
receptor_chains = "A"
receptor_active = "A.937"
ligand_chains = "B"
scoring = "fastdfire"
top=10


#####################################################################-3
[stage.scoring]
flavour = ""
