#===========================================================#
title = "HADDOCK3 Setup file"
#===========================================================#
[molecules]
mol1 = '1AY7_r_u.pdb'
mol2 = '1AY7_l_u.pdb'

[restraints]
ambig = 'ambig-ti.tbl'

[identifier]
run = 1

[execution_parameters]
scheme = 'parallel'
nproc = 24

[stage]
# Stage specific parameters

[stage.topology]
recipe='default'

params.log_level="quiet"

[stage.rigid_body]
recipe='default'
sampling = 10

params.auto_his = true

#[stage.semi_flexible]
#recipe='default'
#sampling = 200

#[stage.water_refinement]
#recipe='default'
#sampling = 200
#===========================================================#