# ====================================================================
# Rigid-body docking example

# in which order the steps must be executed?
order = ["topoaa", "rigidbody", "flexref", "mdref"]

# directory in which the scoring will be done
run_dir = "run1"

# ensemble to be scored
molecules =  [
    "1a2k_l_u.pdb",
    "1a2k_r_u.pdb"
    ]

# ====================================================================
# Parameters for each stage are defined below, prefer full paths
#####################################################################
# WARNING: THE PARAMETERS HERE ARE ILLUSTRATIVE
#  THE WORKFLOW IS WORK-IN-PROGRESS
#####################################################################
[topoaa]
autohis = true

[rigidbody]
ambig = 'ambig.tbl'
sampling = 2

[flexref]
ambig = 'ambig.tbl'
cool1_steps = 500

[mdref]
ambig = 'ambig.tbl'
cool1_steps = 10

# ====================================================================

