# ====================================================================
# Scoring example

# in which order the steps must be executed?
order = ["topology", "scoring"]

# directory in which the scoring will be done
run_dir = "run_simple_scoring"

# ensemble to be scored
molecules = ["T161-rescoring-5.pdb"]

# ====================================================================
[stage]
# Parameters for each stage are defined below

########################
[stage.topology]
autohis = true

########################
[stage.scoring]
