#===========================================================#
title = "HADDOCK3 Scoring Workflow Setup file"
#===========================================================#
# Input molecule is expected to be an ENSAMBLE with ChainIDs
[molecules]
mol1 = 'T158-5random.pdb'

[identifier]
run = 'example'

[execution_parameters]
nproc = 24
scheme = 'parallel'

# Which reference sutructure should be used to calculate RMSDs
reference = 'lowest'

[clustering]
method = 'fcc'
details = false

# Cutoff and Threshold
params = [
    [0.60, 4.0],
    [0.70, 4.0],
    [0.75, 4.0]
]
#===========================================================#
[stage]
[stage.topology]
recipe='default'

[stage.scoring]
recipe='default'

#===========================================================#
