#===========================================================#
title = "HADDOCK3 Scoring Workflow Setup file"
#===========================================================#
# Input molecule is expected to be an ENSAMBLE with ChainIDs
[molecules]
mol1 = 'T161-rescoring-5.pdb'

[identifier]
run = '24-test'

[execution_parameters]
nproc = 24
scheme = 'parallel'

# Which reference sutructure should be used to calculate RMSDs
reference.numbering = '/home/rodrigo/software/haddock3/examples/scoring/capri_48_161.brk'
reference.analysis  = 'lowest'

[clustering]
method = 'fcc'
details = false

# Cutoff and Threshold
params = [
    [0.60, 4.0],
    [0.70, 4.0],
    [0.75, 4.0]
]
#===========================================================#
[stage]
[stage.topology]
recipe='default'

[stage.scoring]
recipe='default'

#===========================================================#
