# ====================================================================
# Scoring example

[input]
# in which order the steps must be executed?
order = ["topology", "scoring", "clustering", "analysis"]

# directory in which the scoring will be done
project_dir = "run1"

# ensemble to be scored
[input.molecules]
mol_1 = "T161-rescoring-5.pdb"

# ====================================================================
[stage]
# Parameters for each stage are defined below

########################
[stage.topology]
autohis = true

########################
[stage.scoring]

########################
[stage.clustering]
method = "fcc"
details = false

# Cutoff and Threshold
params = [
    [0.60, 4.0],
    [0.70, 4.0],
    [0.75, 4.0]
]
########################
[stage.analysis]
template = "capri_48_161.brk"
reference = ""
analysis  = "lowest"
# ====================================================================
