name: integrationtests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CNS_EXEC: ${{ github.workspace }}/bin/cns
  PYTHONPATH: ${{ github.workspace }}/src

jobs:
  integrationtests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install HADDOCK
        run: |
          pwd
          ls -lsa
          mkdir bin
          cd src/fcc/src
          chmod u+x Makefile
          ./Makefile 2>%1 >/dev/null || true
          cd -
          pip install -r requirements.txt

      - name: Install test dependencies
        run: |
          curl ${{ secrets.CNS_LINK }} -o $CNS_EXEC -s
          chmod +x $CNS_EXEC
          pip install pytest

      - name: Run integration test
        run: |
          pytest integration_tests/ -v -x

