name: integration

on: push

env:
  CNS_EXEC: ${{ github.workspace }}/bin/cns
  PYTHONPATH: ${{ github.workspace }}/src

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Install HADDOCK
        run: |
          pwd
          ls -lsa
          mkdir bin
          cd src/fcc/src
          chmod u+x Makefile
          ./Makefile 2>%1 >/dev/null || true
          cd -
          pip install -r requirements.txt

      - run: curl ${{ secrets.CNS_LINK }} -o $CNS_EXEC -s && chmod +x $CNS_EXEC

      - run: pytest integration_tests/ -v -x

