---
# =======================
# DISABLED UNTIL RELEASE #
# =======================
#
name: pages

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
#      - run: echo "temporarily disabled"
      - name: install haddock3 with extra dependencies
        run: pip install '.[dev,docs]'

#       install openmm to render openmm docs properly
      - name: install openmm
            conda install -c conda-forge openmm pdbfixer
            
       - name: Generate docs
       run: |
         sphinx-apidoc -f -e -o docs/ src/haddock -d 1
         sphinx-build -b html docs haddock3-docs

      - name: deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: haddock3-docs
          GITHUB_TOKEN: ${{ secrets.PAGES }}
