---
# =======================
# DISABLED UNTIL RELEASE #
# =======================
#
name: pages

on:
  push:
    branches:
      - main
      - correct_auto_documentation

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: install haddock3 with extra dependencies
        run: pip install '.[dev,docs]'

      - name: install openmm
        run: conda install -c conda-forge openmm pdbfixer

      - name: Generate docs
        run: |
         sphinx-apidoc -f -e -o docs/ src/haddock -d 1
         sphinx-build -b html docs haddock3-docs

#      - name: deploy
#        uses: s0/git-publish-subdir-action@develop
#        env:
#          REPO: self
#          BRANCH: gh-pages
#          FOLDER: haddock3-docs
#          GITHUB_TOKEN: ${{ secrets.PAGES }}
