name: unittests py38

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install coverage[toml] tox
        cd src/fcc/src
        chmod u+x Makefile
        ./Makefile
        cd -
        touch bin/cns


    - name: Test
      run: tox -e py38

    # from https://github.com/codecov/codecov-action
    #- name: Upload coverage to Codecov
    #  uses: codecov/codecov-action@v1
    #  with:
    #    files: ./coverage.xml
    #    fail_ci_if_error: true
    #    verbose: true
