---
name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.9", "3.10", "3.11", "3.12"]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openmpi-bin libopenmpi3 libopenmpi-dev

      - name: install test dependencies
        run: >-
          pip install coverage pytest pytest-cov hypothesis pytest-mock
          fastapi httpx mpi4py

      - name: install haddock3 (development mode)
        run: python setup.py develop

      # - name: check types
      #   run: mypy src/

      - name: run tests
        run: >-
          pytest .
          --cov --cov-report=term-missing --cov-append
          --cov-config=.coveragerc --hypothesis-show-statistics

      - uses: codacy/codacy-coverage-reporter-action@v1
        if: >-
          ${{ github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage.xml
